name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron:  "0 0 * * *"

jobs:
  test:
    name: "Test (node 14)"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3

      - name: "Use Node.js 14"
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: "Install Dependencies"
        run: npm install -g npm && npm install
        continue-on-error: true

      - name: "Run typecheck"
        run: npm run typecheck
        continue-on-error: true

      - name: "Run Tests"
        run: npm run test:unit

  prettify:
    name: "Prettify (Using Prettier)"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js,ts} --ignore-path ./.gitignore
